version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run:
          name: Pull git submodules
          command: |
            git submodule init
            git submodule update
      - run:
          name: Setup cmake
          command: |
            mkdir build
            cd build
            cmake ..
      - run:
          name: Build
          command: |
            cd build
            make
      - run:
          name: Test
          command: |
            cd build
            make test

workflows:
  build-and-test:
    jobs:
      - build-and-test