version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run:
          name: Setup cmake
          command: |
            mkdir build
            cd build
            cmake ..
      - run:
          name: Build
          command: |
            cd build
            make

workflows:
  build:
    jobs:
      - build